Character:
  type: object
  config:
    fields:
      id: "Int"
      name: "String"
      image:
        type: "Image"
        resolve: '@=query("App\\GraphQL\\Resolver\\Images", args["size"], value.getImage())'
        args:
          size:
            type: "String"