Episode:
  type: object
  config:
    fields:
      id: "Int"
      name: "String"
      image:
        type: "Image"
        resolve: '@=query("App\\GraphQL\\Resolver\\Images", args["size"], value.getImage())'
        args:
          size:
            type: "String"
      date: "String"
      description: "String"
      episode_number: "Int"
      season_number: "Int"
      characters:
        type: "[Character!]!"
        resolve: '@=query("App\\GraphQL\\Resolver\\Characters", args["limit"])'
        args:
          limit:
            type: 'Int'
            defaultValue: 4
      watched:
        type: "Boolean"
        resolve: '@=query("App\\GraphQL\\Resolver\\Watched", context, value)'
      rating:
        type: 'String'
        resolve: '@=query("App\\GraphQL\\Resolver\\Rating", context, value)'
