Query:
    type: object
    config:
      fields:
        user:
          type: "User"
          resolve: '@=query("App\\GraphQL\\Resolver\\Users")'
        episodes:
          type: EpisodeConnection
          argsBuilder: "Relay::Connection"
          resolve: '@=query("App\\GraphQL\\Resolver\\Episodes", args)'

EpisodeConnection:
  type: relay-connection
  config:
    nodeType: Episode
#    resolveNode: '@=query("node", value)'
