Query:
    type: object
    config:
      fields:
        user:
          type: "User"
          resolve: '@=query("App\\GraphQL\\Resolver\\Users")'
        episodes:
          type: "[Episode!]!"
          resolve: '@=query("App\\GraphQL\\Resolver\\Episodes", args["limit"])'
          args:
            limit:
              type: 'Int'