version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        TIMEZONE: "Europe/Vilnius"
    container_name: php
    volumes:
      - "./app:/var/www/html"
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - "./app:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - "php"
    networks:
      - app-network

  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mariadb_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
