imports:
  - { resource: 'services/' }

parameters:

services:
  _defaults:
    autowire: false
    autoconfigure: false

#  App\:
#    resource: '../src/'
#    exclude:
#      - '../src/DependencyInjection/'
#      - '../src/Entity/'
#      - '../src/Kernel.php'

  App\GraphQL\Resolver\Users:
    arguments:
      $repository: '@App\Repository\UserRepository'
    tags:
      - { name: overblog_graphql.query}

  App\GraphQL\Resolver\Episodes:
    arguments:
      $repository: '@App\Repository\EpisodeRepository'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Characters:
    arguments:
      $repository: '@App\Repository\CharacterRepository'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Images:
    arguments:
      $imageProvider: '@App\Feature\File\Provider\ImageProvider'
    tags:
      - { name: overblog_graphql.query }

