imports:
  - { resource: 'services/' }

parameters:

services:
  _defaults:
    autowire: false
    autoconfigure: false

#  App\:
#    resource: '../src/'
#    exclude:
#      - '../src/DependencyInjection/'
#      - '../src/Entity/'
#      - '../src/Kernel.php'

  App\GraphQL\Resolver\Users:
    arguments:
      $repository: '@App\Repository\UserRepository'
    tags:
      - { name: overblog_graphql.query}

  App\GraphQL\Resolver\Episodes:
    arguments:
      $repository: '@App\Repository\EpisodeRepository'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Characters:
    arguments:
      $repository: '@App\Repository\CharacterRepository'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Images:
    arguments:
      $imageProvider: '@App\Feature\File\Provider\ImageProvider'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Watched:
    arguments:
      $userRepository: '@App\Repository\UserRepository'
      $loader: '@watched_episodes_dataloader'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Resolver\Rating:
    arguments:
      $userRepository: '@App\Repository\UserRepository'
      $loader: '@watched_episodes_dataloader'
    tags:
      - { name: overblog_graphql.query }

  App\GraphQL\Mutation\AddToWatchedMutation:
    arguments:
      $em: '@Doctrine\ORM\EntityManagerInterface'
      $episodeRepository: '@App\Repository\EpisodeRepository'
      $userRepository: '@App\Repository\UserRepository'
    tags:
      - { name: overblog_graphql.mutation }


  App\GraphQL\Loader\WatchedEpisodesLoader:
    arguments:
      $repository: '@App\Repository\WatchedEpisodeRepository'
      $promiseAdapter: '@overblog_dataloader.webonyx_graphql_sync_promise_adapter'