services:
  App\Feature\FileProvider\ImageProvider:
    arguments:
      $imageRepository: '@App\Repository\File\ImageRepository'
    tags:
      - { name: 'feature.file_provider', provider: 'App\Enum\File\FileProviderEnum::Image' }

  App\Feature\FileProvider\FileContentsProvider:
    arguments:
      $providers: !tagged_iterator { tag: 'feature.file_provider', index_by: 'provider' }
