doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: 'mariadb-10.10.2'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/config/doctrine'
        prefix: 'App\Entity'
        alias: App
        type: xml
      App\Feature\File:
        is_bundle: false
        dir: '%kernel.project_dir%/config/doctrine_file'
        prefix: 'App\Feature\File\Entity'
        alias: App\Feature\File
        type: xml

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
      driver: pdo_sqlite
      path: "%kernel.cache_dir%/test.db"
      url: null

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
